language: node_js
notifications:
- dhiegoduarte@gmail.com
node_js:
# - 0.1
- 8.7.0
services:
- mongodb
env:
  global:
  - NODE_ENV: test
addons:
  sauce_connect: true
  # chrome: stable
before_install:
- rvm install 1.9.3
- travis_internal_ruby() { echo "1.9.3"; }
- npm install -g bower@1.3
- npm install -g grunt-cli@0.1
- npm install -g karma-cli@0.0
- npm install -g protractor@1.5
- webdriver-manager update
- bower install
- npm install karma-jasmine --save-dev
before_script:
- node test/data.js
- grunt minifica
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
- node server &
- protractor config/protractor.js
# before_deploy:
# - git config --global user.email 'travis@travis-ci.com'
# - git config --global user.name 'Travis CI'
# - git checkout $TRAVIS_BRANCH
# - git add --all
# - git commit -am "Travis commit"
# deploy:
#   provider: openshift
#   user: bruno.m.gasparotto@gmail.com
#   password: yomate666
#   app: contatooh
#   domain: bgasparotto
#   on:
#     repo: dhiegoduarte/contatooh
